# SPDX-License-Identifier: PMPL-1.0-or-later
[workspace]
members = [
    "hardware-crash-team",
    "clinician",
    "contracts-rust",
    "port-endoscope",
    "emergency-button/rust",
    "emergency-room/rust",
]
exclude = ["personal-sysadmin", "displace", "panoptes", "_pathroot/rust/mustfile-orchestrator", "ambulances/network"]
resolver = "2"

[workspace.dependencies]
proptest = "1.4"
criterion = "0.5"

[profile.release]
lto = true
codegen-units = 1
strip = true
