# SPDX-License-Identifier: MPL-2.0
defmodule HAR.DataPlane.Transformers.CloudFormationTest do
  @moduledoc """
  Tests for the AWS CloudFormation template transformer.

  Verifies that semantic graph operations are correctly converted to
  CloudFormation YAML/JSON templates with proper resource types,
  properties, DependsOn relationships, and template structure.
  """

  use ExUnit.Case, async: true

  alias HAR.DataPlane.Transformers.CloudFormation
  alias HAR.Semantic.{Graph, Operation, Dependency}

  describe "transform/2 - EC2 instances" do
    test "transforms vm_create to AWS::EC2::Instance" do
      graph =
        build_graph([
          Operation.new(:vm_create, %{
            name: "web-server",
            instance_type: "t3.micro",
            image_id: "ami-12345678"
          })
        ])

      assert {:ok, output} = CloudFormation.transform(graph)
      assert is_binary(output)
      assert output =~ "AWS::EC2::Instance"
      assert output =~ "t3.micro"
    end
  end

  describe "transform/2 - S3 buckets" do
    test "transforms storage_bucket_create to AWS::S3::Bucket" do
      graph =
        build_graph([
          Operation.new(:storage_bucket_create, %{
            name: "my-data-bucket"
          })
        ])

      assert {:ok, output} = CloudFormation.transform(graph)
      assert is_binary(output)
      assert output =~ "AWS::S3::Bucket"
      assert output =~ "my-data-bucket"
    end
  end

  describe "transform/2 - Lambda functions" do
    test "transforms function_create to AWS::Lambda::Function" do
      graph =
        build_graph([
          Operation.new(:function_create, %{
            name: "process-events",
            runtime: "python3.12",
            handler: "index.handler"
          })
        ])

      assert {:ok, output} = CloudFormation.transform(graph)
      assert is_binary(output)
      assert output =~ "AWS::Lambda::Function"
      assert output =~ "python3.12"
    end
  end

  describe "transform/2 - RDS databases" do
    test "transforms database_create to AWS::RDS::DBInstance" do
      graph =
        build_graph([
          Operation.new(:database_create, %{
            name: "app-db",
            engine: "postgres",
            instance_class: "db.t3.micro"
          })
        ])

      assert {:ok, output} = CloudFormation.transform(graph)
      assert is_binary(output)
      assert output =~ "AWS::RDS::DBInstance"
      assert output =~ "postgres"
    end
  end

  describe "transform/2 - VPC networking" do
    test "transforms network_vpc_create to AWS::EC2::VPC" do
      graph =
        build_graph([
          Operation.new(:network_vpc_create, %{
            name: "main-vpc",
            cidr_block: "10.0.0.0/16"
          })
        ])

      assert {:ok, output} = CloudFormation.transform(graph)
      assert is_binary(output)
      assert output =~ "AWS::EC2::VPC"
      assert output =~ "10.0.0.0/16"
    end

    test "transforms security_group_create to AWS::EC2::SecurityGroup" do
      graph =
        build_graph([
          Operation.new(:security_group_create, %{
            name: "web-sg",
            description: "Allow HTTP/HTTPS"
          })
        ])

      assert {:ok, output} = CloudFormation.transform(graph)
      assert output =~ "AWS::EC2::SecurityGroup"
    end
  end

  describe "transform/2 - template structure" do
    test "includes AWSTemplateFormatVersion" do
      graph =
        build_graph([
          Operation.new(:storage_bucket_create, %{name: "test-bucket"})
        ])

      assert {:ok, output} = CloudFormation.transform(graph)
      assert output =~ "2010-09-09"
    end

    test "includes Description field" do
      graph =
        build_graph([
          Operation.new(:storage_bucket_create, %{name: "test-bucket"})
        ])

      assert {:ok, output} = CloudFormation.transform(graph, description: "My Stack")
      assert output =~ "My Stack"
    end

    test "includes HAR generation comment" do
      graph =
        build_graph([
          Operation.new(:storage_bucket_create, %{name: "test-bucket"})
        ])

      assert {:ok, output} = CloudFormation.transform(graph)
      assert output =~ "Generated by HAR"
      assert output =~ "CloudFormation"
    end
  end

  describe "transform/2 - multiple resources" do
    test "produces template with multiple resources" do
      graph =
        build_graph([
          Operation.new(:network_vpc_create, %{name: "vpc", cidr_block: "10.0.0.0/16"}),
          Operation.new(:network_subnet_create, %{name: "subnet", cidr_block: "10.0.1.0/24"}),
          Operation.new(:security_group_create, %{name: "sg", description: "SG"})
        ])

      assert {:ok, output} = CloudFormation.transform(graph)
      assert output =~ "AWS::EC2::VPC"
      assert output =~ "AWS::EC2::Subnet"
      assert output =~ "AWS::EC2::SecurityGroup"
    end
  end

  describe "transform/2 - JSON format" do
    test "produces JSON when format: :json is specified" do
      graph =
        build_graph([
          Operation.new(:storage_bucket_create, %{name: "json-bucket"})
        ])

      assert {:ok, output} = CloudFormation.transform(graph, format: :json)
      assert is_binary(output)
      # JSON output should be parseable
      assert output =~ "AWSTemplateFormatVersion"
    end
  end

  describe "validate/1" do
    test "validates a well-formed graph" do
      graph =
        build_graph([
          Operation.new(:vm_create, %{name: "server", instance_type: "t3.micro"})
        ])

      assert :ok = CloudFormation.validate(graph)
    end
  end

  # Helper to build a test graph from a list of operations
  defp build_graph(operations) do
    Graph.new(
      vertices: operations,
      edges: [],
      metadata: %{source: :test}
    )
  end
end
