# SPDX-License-Identifier: MPL-2.0
defmodule HAR.DataPlane.Transformers.DockerComposeTest do
  @moduledoc """
  Tests for the Docker Compose transformer.

  Verifies that semantic graph operations are correctly converted to
  Docker Compose YAML format with services, networks, volumes,
  port mappings, environment variables, and dependency chains.
  """

  use ExUnit.Case, async: true

  alias HAR.DataPlane.Transformers.DockerCompose
  alias HAR.Semantic.{Graph, Operation}

  describe "transform/2 - container services" do
    test "transforms container_run to service with image" do
      graph =
        build_graph([
          Operation.new(:container_run, %{
            name: "web",
            image: "nginx:latest",
            ports: [%{published: 8080, target: 80}]
          })
        ])

      assert {:ok, output} = DockerCompose.transform(graph)
      assert is_binary(output)
      assert output =~ "services"
      assert output =~ "web"
      assert output =~ "nginx:latest"
    end

    test "transforms container_run with environment variables" do
      graph =
        build_graph([
          Operation.new(:container_run, %{
            name: "api",
            image: "api:v1",
            environment: %{"NODE_ENV" => "production", "PORT" => "3000"}
          })
        ])

      assert {:ok, output} = DockerCompose.transform(graph)
      assert is_binary(output)
      assert output =~ "environment"
      assert output =~ "NODE_ENV"
    end

    test "transforms container_run with volumes" do
      graph =
        build_graph([
          Operation.new(:container_run, %{
            name: "db",
            image: "postgres:15",
            volumes: [%{source: "pgdata", target: "/var/lib/postgresql/data"}]
          })
        ])

      assert {:ok, output} = DockerCompose.transform(graph)
      assert is_binary(output)
      assert output =~ "volumes"
      assert output =~ "pgdata"
    end

    test "transforms container_run with restart policy" do
      graph =
        build_graph([
          Operation.new(:container_run, %{
            name: "worker",
            image: "worker:latest",
            restart: "unless-stopped"
          })
        ])

      assert {:ok, output} = DockerCompose.transform(graph)
      assert output =~ "restart"
      assert output =~ "unless-stopped"
    end
  end

  describe "transform/2 - networks" do
    test "transforms network_create to top-level networks entry" do
      graph =
        build_graph([
          Operation.new(:network_create, %{
            name: "backend-net",
            driver: "bridge"
          })
        ])

      assert {:ok, output} = DockerCompose.transform(graph)
      assert is_binary(output)
      assert output =~ "networks"
      assert output =~ "backend-net"
    end
  end

  describe "transform/2 - volumes" do
    test "transforms storage_volume_create to top-level volumes entry" do
      graph =
        build_graph([
          Operation.new(:storage_volume_create, %{
            name: "data-vol",
            driver: "local"
          })
        ])

      assert {:ok, output} = DockerCompose.transform(graph)
      assert is_binary(output)
      assert output =~ "volumes"
      assert output =~ "data-vol"
    end
  end

  describe "transform/2 - multiple services" do
    test "produces compose file with multiple services" do
      graph =
        build_graph([
          Operation.new(:container_run, %{
            name: "web",
            image: "nginx:latest"
          }),
          Operation.new(:container_run, %{
            name: "api",
            image: "node:20"
          }),
          Operation.new(:container_run, %{
            name: "db",
            image: "postgres:15"
          })
        ])

      assert {:ok, output} = DockerCompose.transform(graph)
      assert is_binary(output)
      assert output =~ "web"
      assert output =~ "api"
      assert output =~ "db"
    end
  end

  describe "transform/2 - HAR header" do
    test "includes HAR and Docker Compose generation comment" do
      graph =
        build_graph([
          Operation.new(:container_run, %{name: "test", image: "busybox"})
        ])

      assert {:ok, output} = DockerCompose.transform(graph)
      assert output =~ "Generated by HAR"
      assert output =~ "Docker Compose"
    end
  end

  describe "validate/1" do
    test "validates a well-formed graph" do
      graph =
        build_graph([
          Operation.new(:container_run, %{name: "web", image: "nginx"})
        ])

      assert :ok = DockerCompose.validate(graph)
    end
  end

  # Helper to build a test graph from a list of operations
  defp build_graph(operations) do
    Graph.new(
      vertices: operations,
      edges: [],
      metadata: %{source: :test}
    )
  end
end
