# SPDX-License-Identifier: MPL-2.0
defmodule HAR.DataPlane.Transformers.PuppetTest do
  @moduledoc """
  Tests for the Puppet manifest transformer.

  Verifies that semantic graph operations are correctly converted to
  Puppet DSL (.pp) format with resource declarations, ensure states,
  relationship metaparameters, and class wrapper generation.
  """

  use ExUnit.Case, async: true

  alias HAR.DataPlane.Transformers.Puppet
  alias HAR.Semantic.{Graph, Operation, Dependency}

  describe "transform/2 - package operations" do
    test "transforms package_install to package resource with ensure present" do
      graph =
        build_graph([
          Operation.new(:package_install, %{name: "nginx"})
        ])

      assert {:ok, output} = Puppet.transform(graph)
      assert is_binary(output)
      assert output =~ "package"
      assert output =~ "nginx"
      assert output =~ "ensure"
      assert output =~ "present"
    end

    test "transforms package_remove to package resource with ensure absent" do
      graph =
        build_graph([
          Operation.new(:package_remove, %{name: "apache2"})
        ])

      assert {:ok, output} = Puppet.transform(graph)
      assert output =~ "package"
      assert output =~ "absent"
    end

    test "transforms package_upgrade to package resource with ensure latest" do
      graph =
        build_graph([
          Operation.new(:package_upgrade, %{name: "openssl"})
        ])

      assert {:ok, output} = Puppet.transform(graph)
      assert output =~ "package"
      assert output =~ "latest"
    end
  end

  describe "transform/2 - service operations" do
    test "transforms service_start to service resource with ensure running" do
      graph =
        build_graph([
          Operation.new(:service_start, %{name: "nginx"})
        ])

      assert {:ok, output} = Puppet.transform(graph)
      assert is_binary(output)
      assert output =~ "service"
      assert output =~ "nginx"
      assert output =~ "running"
    end

    test "transforms service_stop to service resource with ensure stopped" do
      graph =
        build_graph([
          Operation.new(:service_stop, %{name: "apache2"})
        ])

      assert {:ok, output} = Puppet.transform(graph)
      assert output =~ "service"
      assert output =~ "stopped"
    end
  end

  describe "transform/2 - user operations" do
    test "transforms user_create to user resource with ensure present" do
      graph =
        build_graph([
          Operation.new(:user_create, %{name: "deploy", shell: "/bin/bash"})
        ])

      assert {:ok, output} = Puppet.transform(graph)
      assert is_binary(output)
      assert output =~ "user"
      assert output =~ "deploy"
      assert output =~ "present"
      assert output =~ "/bin/bash"
    end
  end

  describe "transform/2 - exec operations" do
    test "transforms command_run to exec resource" do
      graph =
        build_graph([
          Operation.new(:command_run, %{
            name: "reload-systemd",
            command: "systemctl daemon-reload"
          })
        ])

      assert {:ok, output} = Puppet.transform(graph)
      assert is_binary(output)
      assert output =~ "exec"
      assert output =~ "systemctl daemon-reload"
    end
  end

  describe "transform/2 - class wrapping" do
    test "wraps resources in class when class_name option given" do
      graph =
        build_graph([
          Operation.new(:package_install, %{name: "nginx"})
        ])

      assert {:ok, output} = Puppet.transform(graph, class_name: "webserver")
      assert output =~ "class webserver"
    end

    test "outputs resources without class when no class_name" do
      graph =
        build_graph([
          Operation.new(:package_install, %{name: "nginx"})
        ])

      assert {:ok, output} = Puppet.transform(graph)
      refute output =~ "class "
    end
  end

  describe "transform/2 - HAR header comment" do
    test "includes HAR generation comment" do
      graph =
        build_graph([
          Operation.new(:package_install, %{name: "curl"})
        ])

      assert {:ok, output} = Puppet.transform(graph)
      assert output =~ "Generated by HAR"
    end
  end

  describe "transform/2 - multiple operations" do
    test "renders multiple resource blocks" do
      graph =
        build_graph([
          Operation.new(:package_install, %{name: "nginx"}),
          Operation.new(:service_start, %{name: "nginx"}),
          Operation.new(:user_create, %{name: "www-data"})
        ])

      assert {:ok, output} = Puppet.transform(graph)
      assert output =~ "package"
      assert output =~ "service"
      assert output =~ "user"
    end
  end

  describe "validate/1" do
    test "validates a well-formed graph" do
      graph = build_graph([Operation.new(:package_install, %{name: "nginx"})])
      assert :ok = Puppet.validate(graph)
    end
  end

  # Helper to build a test graph from a list of operations
  defp build_graph(operations) do
    Graph.new(
      vertices: operations,
      edges: [],
      metadata: %{source: :test}
    )
  end
end
