# eclexiaiser manifest — energy/carbon resource budgets
# SPDX-License-Identifier: MPL-2.0

[project]
name = "displace"

[[functions]]
name = "copy_dir_recursive"
source = "src/main.rs"
energy-budget-mj = 35.0
carbon-budget-mg = 7.0

[[functions]]
name = "main"
source = "src/main.rs"
energy-budget-mj = 15.0
carbon-budget-mg = 3.0

[carbon]
provider = "static"
region = "GB"
static-intensity = 200.0

[report]
format = "text"
include-recommendations = true
