;; SPDX-License-Identifier: AGPL-3.0-or-later
;; ECOSYSTEM.scm - Ecosystem position for ambientops
;; Media-Type: application/vnd.ecosystem+scm

(ecosystem
  (version "1.0")
  (name "ambientops")
  (type "umbrella-platform")
  (purpose "Ambient computing operations platform - unified control plane for distributed systems, CI/CD automation, and system resilience")

  (position-in-ecosystem
    (category "platform-infrastructure")
    (subcategory "ambient-computing")
    (unique-value
      ("Hospital Model: triage, diagnosis, treatment, prevention")
      ("Neurosymbolic automation: neural learning + symbolic execution")
      ("Cross-forge CI/CD orchestration")
      ("System resilience: freeze-ejector + flare for crash recovery")
      ("Hook wave propagation for atomic multi-repo updates")))

  (related-projects
    ;; Core satellites - CI/CD
    (project "cicd-hyper-a"
      (relationship "satellite")
      (category "ci-cd-automation")
      (description "Neurosymbolic CI/CD automation with Logtalk rule engine")
      (status "active")
      (integration "Main automation engine - generates hooks, enforces security"))

    (project "gitvisor"
      (relationship "satellite")
      (category "monitoring")
      (description "Git repository supervision and monitoring")
      (status "active")
      (integration "Monitors repos, feeds data to cicd-hyper-a"))

    (project ".git-private-farm"
      (relationship "satellite")
      (category "infrastructure")
      (description "Private git hook and template distribution")
      (status "active")
      (integration "Distributes hooks generated by cicd-hyper-a"))

    ;; Core satellites - System Resilience
    (project "system-freeze-ejector"
      (relationship "planned-satellite")
      (category "system-resilience")
      (description "Off-machine kernel dump for system recovery")
      (status "planned")
      (integration "Preserves state during system crashes, enables recovery")
      (concept "Off-machine kernel dump to networked storage or USB"))

    (project "system-flare"
      (relationship "planned-satellite")
      (category "system-resilience")
      (description "Rapid system halt with state preservation")
      (status "planned")
      (integration "Emergency stop that saves work-in-progress before halt")
      (concept "Quick-access panic button with graceful state dump"))

    ;; Knowledge/Learning satellites
    (project "repo-slm-augmentor"
      (relationship "satellite")
      (category "knowledge-base")
      (description "SLM augmentation for security knowledge")
      (status "active")
      (integration "Provides Logtalk security_errors.lgt knowledge base"))

    ;; Notification satellites
    (project "echidnabot"
      (relationship "satellite")
      (category "notifications")
      (description "Discord bot for CI/CD notifications")
      (status "active")
      (integration "Reports issues from cicd-hyper-a"))

    (project "rhodibot"
      (relationship "satellite")
      (category "dashboard")
      (description "Repository health dashboard bot")
      (status "active")
      (integration "Displays metrics from ambientops components"))

    ;; Hospital Model components
    (project "system-emergency-room"
      (relationship "satellite")
      (category "hospital-model")
      (description "Immediate triage and stabilization")
      (status "active")
      (integration "First responder for critical issues"))

    (project "system-observatory"
      (relationship "satellite")
      (category "hospital-model")
      (description "Long-term monitoring and trend analysis")
      (status "active")
      (integration "Feeds insights back to prevention layer")))

  (what-this-is
    ("Umbrella platform for ambient computing operations")
    ("Hospital Model for system health: triage, diagnosis, treatment, prevention")
    ("Coordination layer for distributed automation satellites")
    ("Unified control plane for CI/CD, monitoring, and resilience")
    ("Neurosymbolic platform: neural learning feeds symbolic automation"))

  (what-this-is-not
    ("Not a single monolithic application")
    ("Not a replacement for GitHub/GitLab - works alongside them")
    ("Not an observability platform - delegates to dedicated satellites")
    ("Not a cloud provider - manages existing infrastructure")))
